#!/usr/bin/python -u

try:
    import autotest.common as common
except ImportError:
    import common

from autotest.mcp import run_gateway


if __name__ == '__main__':
    raise SystemExit(run_gateway.main())
